/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Props_Base_1: THREE.Mesh
        Props_Base_2: THREE.Mesh
        Props_Base_3: THREE.Mesh
        ['Node-Mesh001']: THREE.Mesh
        ['Node-Mesh001_1']: THREE.Mesh
        ['Node-Mesh001_2']: THREE.Mesh
        sidescreenScreen: THREE.Mesh
        billboard001: THREE.Mesh
        billboard002: THREE.Mesh
    }
    materials: {
        DarkGrey: THREE.MeshStandardMaterial
        Main: THREE.MeshStandardMaterial
        Accent: THREE.MeshStandardMaterial
        mat17: THREE.MeshStandardMaterial
        mat18: THREE.MeshStandardMaterial
        mat22: THREE.MeshStandardMaterial
        mat23: THREE.MeshStandardMaterial
        billbordScrren: THREE.MeshStandardMaterial
    }
}

export function BillBoardSet6(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/billboardSet6.glb') as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <group name="telepad" position={[-0.067, 0, -0.063]}>
                    <group name="Props_Base" position={[0.537, 0.101, 0.821]} scale={98.291}>
                        <mesh
                            name="Props_Base_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Props_Base_1.geometry}
                            material={materials.DarkGrey}
                        />
                        <mesh
                            name="Props_Base_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Props_Base_2.geometry}
                            material={materials.Main}
                        />
                        <mesh
                            name="Props_Base_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.Props_Base_3.geometry}
                            material={materials.Accent}
                        />
                    </group>
                </group>
                <group
                    name="billboard"
                    position={[1.746, 2.164, -1.469]}
                    rotation={[0, 1.571, 0]}
                    scale={[5.627, 5.627, 5.948]}>
                    <mesh
                        name="Node-Mesh001"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001'].geometry}
                        material={materials.mat17}
                    />
                    <mesh
                        name="Node-Mesh001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_1'].geometry}
                        material={materials.mat18}
                    />
                    <mesh
                        name="Node-Mesh001_2"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_2'].geometry}
                        material={materials.mat22}
                    />
                </group>
                <mesh
                    name="sidescreenScreen"
                    castShadow
                    receiveShadow
                    geometry={nodes.sidescreenScreen.geometry}
                    material={materials.mat23}
                    position={[-1.857, 3.652, -0.187]}
                    rotation={[Math.PI, -0.79, Math.PI]}
                    scale={[4.904, 4.311, 3.377]}
                />
                <mesh
                    name="billboard001"
                    castShadow
                    receiveShadow
                    geometry={nodes.billboard001.geometry}
                    material={materials.billbordScrren}
                    position={[1.767, 3.375, -1.305]}
                    rotation={[0, 1.571, 0]}
                    scale={[5.627, 5.627, 5.948]}
                />
                <mesh
                    name="billboard002"
                    castShadow
                    receiveShadow
                    geometry={nodes.billboard002.geometry}
                    material={materials.billbordScrren}
                    position={[-1.89, 3.65, -0.213]}
                    rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                    scale={5.532}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/billboardSet6.glb')
