/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { billboards } from '@/lib/billBoardData'
import { useGLTF } from '@react-three/drei'
import { useEffect, useState } from 'react'
import BillBoardPrimitive from './BillBoardPrimitive'

export function BillBoardSetMultiple3(props: JSX.IntrinsicElements['group']) {
    const [first, setfirst] = useState<string | TrustedHTML>("")

    useEffect(() => {
        const url = 'http://localhost:3000/github-web'; // Replace with the target website
        const fetchData = async () => {
            try {
                const response = await fetch(url);
                const html = await response.text();

                // const cleanHtml = DOMPurify.sanitize(html);
                // const parser = new DOMParser();
                // const doc = parser.parseFromString(html, 'text/html');

                // console.log({ cleanHtml });
                setfirst(html)

            } catch (error) {
                console.log(error);
            }
        }
        fetchData()


        return () => {

        }
    }, [])


    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <BillBoardPrimitive first={first} billboards={billboards} />
            </group>
        </group>
    )
}

useGLTF.preload('/billboardSetmultiple.glb')


