/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Props_Base_1: THREE.Mesh
        Props_Base_2: THREE.Mesh
        Props_Base_3: THREE.Mesh
        sidescreen: THREE.Mesh
        ['Node-Mesh001']: THREE.Mesh
        ['Node-Mesh001_1']: THREE.Mesh
        ['Node-Mesh001_2']: THREE.Mesh
        ['Node-Mesh001_3']: THREE.Mesh
        ['Node-Mesh001_4']: THREE.Mesh
        ['Node-Mesh001_5']: THREE.Mesh
        sidescreenScreen: THREE.Mesh
    }
    materials: {
        DarkGrey: THREE.MeshStandardMaterial
        Main: THREE.MeshStandardMaterial
        Accent: THREE.MeshStandardMaterial
        mat24: THREE.MeshStandardMaterial
        mat17: THREE.MeshStandardMaterial
        billbordScrren: THREE.MeshStandardMaterial
        mat18: THREE.MeshStandardMaterial
        mat22: THREE.MeshStandardMaterial
        mat12: THREE.MeshStandardMaterial
        ['mat24.001']: THREE.MeshStandardMaterial
        mat23: THREE.MeshStandardMaterial
    }
}

export function BillboardSet2(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/billboardSet2.glb') as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <group name="telepad" position={[-0.1, 0, -0.1]}>
                    <group name="Props_Base" position={[0.1, 0, 0.1]} scale={9.4}>
                        <mesh
                            name="Props_Base_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Props_Base_1.geometry}
                            material={materials.DarkGrey}
                        />
                        <mesh
                            name="Props_Base_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Props_Base_2.geometry}
                            material={materials.Main}
                        />
                        <mesh
                            name="Props_Base_3"
                            castShadow
                            receiveShadow
                            geometry={nodes.Props_Base_3.geometry}
                            material={materials.Accent}
                        />
                    </group>
                </group>
                <mesh
                    name="sidescreen"
                    castShadow
                    receiveShadow
                    geometry={nodes.sidescreen.geometry}
                    material={materials.mat24}
                    position={[-0.4, 0.5, -0.2]}
                    rotation={[Math.PI, -0.8, Math.PI]}
                    scale={[0.9, 0.8, 0.6]}
                />
                <group name="billboard" position={[0.2, 0.2, -0.3]} rotation={[0, 1.6, 0]}>
                    <mesh
                        name="Node-Mesh001"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001'].geometry}
                        material={materials.mat17}
                    />
                    <mesh
                        name="Node-Mesh001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_1'].geometry}
                        material={materials.billbordScrren}
                    />
                    <mesh
                        name="Node-Mesh001_2"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_2'].geometry}
                        material={materials.mat18}
                    />
                    <mesh
                        name="Node-Mesh001_3"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_3'].geometry}
                        material={materials.mat22}
                    />
                    <mesh
                        name="Node-Mesh001_4"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_4'].geometry}
                        material={materials.mat12}
                    />
                    <mesh
                        name="Node-Mesh001_5"
                        castShadow
                        receiveShadow
                        geometry={nodes['Node-Mesh001_5'].geometry}
                        material={materials['mat24.001']}
                    />
                </group>
                <mesh
                    name="sidescreenScreen"
                    castShadow
                    receiveShadow
                    geometry={nodes.sidescreenScreen.geometry}
                    material={materials.mat23}
                    position={[-0.4, 0.5, -0.2]}
                    rotation={[Math.PI, -0.8, Math.PI]}
                    scale={[0.9, 0.8, 0.6]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/billboardSet2.glb')
