/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier'

type GLTFResult = GLTF & {
    nodes: {
        Props_Base_1: THREE.Mesh
        Props_Base_2: THREE.Mesh
        Props_Base_3: THREE.Mesh
        sidescreen: THREE.Mesh
        ['Node-Mesh001']: THREE.Mesh
        ['Node-Mesh001_1']: THREE.Mesh
        ['Node-Mesh001_2']: THREE.Mesh
        ['Node-Mesh001_3']: THREE.Mesh
        ['Node-Mesh001_4']: THREE.Mesh
        sidescreenScreen: THREE.Mesh
        billboard001: THREE.Mesh
    }
    materials: {
        DarkGrey: THREE.MeshStandardMaterial
        Main: THREE.MeshStandardMaterial
        Accent: THREE.MeshStandardMaterial
        mat24: THREE.MeshStandardMaterial
        mat17: THREE.MeshStandardMaterial
        mat18: THREE.MeshStandardMaterial
        mat22: THREE.MeshStandardMaterial
        mat12: THREE.MeshStandardMaterial
        ['mat24.001']: THREE.MeshStandardMaterial
        mat23: THREE.MeshStandardMaterial
        billbordScrren: THREE.MeshStandardMaterial
    }
}

export function BillboardSet3(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/billboardSet3.glb') as GLTFResult

    const handleCollision = () => {
        console.log('collisiob with pad');

    }
    return (
        <group {...props} dispose={null}>
            <group name="Scene" >
                <RigidBody onCollisionEnter={handleCollision} type="fixed"  >
                    <group name="telepad" position={[-0.067, 0, -0.063]}>
                        <group name="Props_Base" position={[0.062, 0.017, 0.062]} scale={9.357}>
                            <mesh
                                name="Props_Base_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Props_Base_1.geometry}
                                material={materials.DarkGrey}
                            />
                            <mesh
                                name="Props_Base_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Props_Base_2.geometry}
                                material={materials.Main}
                            />
                            <mesh
                                name="Props_Base_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Props_Base_3.geometry}
                                material={materials.Accent}
                            />
                        </group>
                    </group></RigidBody>
                <RigidBody type="fixed" colliders='hull' >
                    <mesh
                        name="sidescreen"
                        castShadow
                        receiveShadow
                        geometry={nodes.sidescreen.geometry}
                        // material={materials.mat24}
                        position={[-0.391, 0.541, -0.232]}
                        rotation={[Math.PI, -0.79, Math.PI]}
                        scale={[0.872, 0.766, 0.6]}
                    >

                        <meshStandardMaterial color='red' />

                    </mesh>


                    <group name="billboard" position={[0.233, 0.167, -0.262]} rotation={[0, 1.571, 0]}>
                        <mesh
                            name="Node-Mesh001"
                            castShadow
                            receiveShadow
                            geometry={nodes['Node-Mesh001'].geometry}
                            material={materials.mat17}
                        />
                        <mesh
                            name="Node-Mesh001_1"
                            castShadow
                            receiveShadow
                            geometry={nodes['Node-Mesh001_1'].geometry}
                            material={materials.mat18}
                        />
                        <mesh
                            name="Node-Mesh001_2"
                            castShadow
                            receiveShadow
                            geometry={nodes['Node-Mesh001_2'].geometry}
                            material={materials.mat22}
                        />
                        <mesh
                            name="Node-Mesh001_3"
                            castShadow
                            receiveShadow
                            geometry={nodes['Node-Mesh001_3'].geometry}
                            material={materials.mat12}
                        />
                        <mesh
                            name="Node-Mesh001_4"
                            castShadow
                            receiveShadow
                            geometry={nodes['Node-Mesh001_4'].geometry}
                            material={materials['mat24.001']}
                        />
                    </group>
                    <mesh
                        name="sidescreenScreen"
                        castShadow
                        receiveShadow
                        geometry={nodes.sidescreenScreen.geometry}
                        material={materials.mat23}
                        position={[-0.389, 0.455, -0.226]}
                        rotation={[Math.PI, -0.79, Math.PI]}
                        scale={[0.872, 0.766, 0.6]}
                    />

                    <mesh
                        name="billboard001"
                        castShadow
                        receiveShadow
                        geometry={nodes.billboard001.geometry}
                        // material={materials.billbordScrren}
                        position={[0.225, 0.327, -0.367]}
                        rotation={[0, 1.571, 0]}
                    >
                        <meshStandardMaterial color='red' />
                    </mesh>

                </RigidBody>
            </group>
        </group>
    )
}

useGLTF.preload('/billboardSet3.glb')
